Traceback (most recent call last):
  File "/opt/anaconda3/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Note this can be copied from examples in chapter 0 ("prepwork")
nSamples = 10000 # we will draw 10,000 samples
samplesize=[3,4,5] # each sample contains n people

for j in range(len(samplesize)):
    m=np.empty(nSamples) # make an array to store the means

    for i in range(nSamples):
        # Your code here to fill in m with sample means
        sample = UKBrexdex.sample(n=samplesize, replace=False)
        m[i]=sample.score.mean()
        
    plt.subplot(3,1,j+1)
    sns.histplot(m, bins=range(0,100,5))
    plt.xlabel('sample mean')

plt.tight_layout()
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[12], line 10[0m
[1;32m      6[0m m[38;5;241m=[39mnp[38;5;241m.[39mempty(nSamples) [38;5;66;03m# make an array to store the means[39;00m
[1;32m      8[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m(nSamples):
[1;32m      9[0m     [38;5;66;03m# Your code here to fill in m with sample means[39;00m
[0;32m---> 10[0m     sample [38;5;241m=[39m UKBrexdex[38;5;241m.[39msample(n[38;5;241m=[39msamplesize, replace[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[1;32m     11[0m     m[i][38;5;241m=[39msample[38;5;241m.[39mscore[38;5;241m.[39mmean()
[1;32m     13[0m plt[38;5;241m.[39msubplot([38;5;241m3[39m,[38;5;241m1[39m,j[38;5;241m+[39m[38;5;241m1[39m)

File [0;32m/opt/anaconda3/anaconda3/lib/python3.11/site-packages/pandas/core/generic.py:6021[0m, in [0;36mNDFrame.sample[0;34m(self, n, frac, replace, weights, random_state, axis, ignore_index)[0m
[1;32m   6018[0m [38;5;66;03m# Process random_state argument[39;00m
[1;32m   6019[0m rs [38;5;241m=[39m common[38;5;241m.[39mrandom_state(random_state)
[0;32m-> 6021[0m size [38;5;241m=[39m sample[38;5;241m.[39mprocess_sampling_size(n, frac, replace)
[1;32m   6022[0m [38;5;28;01mif[39;00m size [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m   6023[0m     [38;5;28;01massert[39;00m frac [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m

File [0;32m/opt/anaconda3/anaconda3/lib/python3.11/site-packages/pandas/core/sample.py:96[0m, in [0;36mprocess_sampling_size[0;34m(n, frac, replace)[0m
[1;32m     94[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mPlease enter a value for `frac` OR `n`, not both[39m[38;5;124m"[39m)
[1;32m     95[0m [38;5;28;01melif[39;00m n [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m---> 96[0m     [38;5;28;01mif[39;00m n [38;5;241m<[39m [38;5;241m0[39m:
[1;32m     97[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m     98[0m             [38;5;124m"[39m[38;5;124mA negative number of rows requested. Please provide `n` >= 0.[39m[38;5;124m"[39m
[1;32m     99[0m         )
[1;32m    100[0m     [38;5;28;01mif[39;00m n [38;5;241m%[39m [38;5;241m1[39m [38;5;241m!=[39m [38;5;241m0[39m:

[0;31mTypeError[0m: '<' not supported between instances of 'list' and 'int'

